### ISSUE TITLE
For discussion: add `shortbooktitle` field to the meta file

### ISSUE THREAD

**Issue by mjpost** [acl-org/ACLPUB#22]
It would be nice if we got pubchairs to decide on a short name for each volume, which could then be used in papers etc. If there is agreement on this, we could ask Softconf to add that field to the START interface, and we could update the code to process it. See also https://github.com/acl-org/acl-anthology/pull/567.

**Comment by davidweichiang** [comment]
The meta file has a field called `abbrev` which looks to me like it used to be the short name of the conference series, e.g., "EMNLP", but is now usually set to the Anthology prefix, e.g., "D19-1". However, this is redundant because the `bib_url` also contains the Anthology prefix. One option would simply be to revert `abbrev` to "EMNLP". This would just involve updating the instructions and updating the code to get the Anthology prefix from `bib_url` instead of `abbrev`.

The meta file also has a field `type` which looks like it might only be used in HTML generation, which no longer gets used. It has values like "Conference", "Main Conference", "Demos", etc. That field could be used once again to generate the volume title.

Those pieces of information, together with possibly the year (which is also in meta), could be used to generate a shortbooktitle, right?

**Comment by mjpost** [comment]
I was thinking that we should use “abbrev” as the identifier in the new IDs. We will no longer need bib_url at all once that is in place. 

Are you suggesting this to reconstruct past short volumes or as a way into the future? I am not sure that people have reliably used “type” in the past. I’d rather ask for a short title than try to programmatically cobble one together but maybe I’m not thinking of something.

**Comment by davidweichiang** [comment]
Oh, getting rid of bib_url sounds great. 

I don’t think there’s any need to reconstruct shortbooktitles from old meta files, but my preference for programmatically constructing the short title is because I think it may be hard to make a shortbooktitle that all users like.

**Comment by mjpost** [comment]
Closing as this can now be handled in the Anthology.
